server:
  port: 8080
  servlet:
    context-path: /alura

spring:
  application:
    name: alura-challenge
  devtools:
    add-properties: false
  profiles:
    default: prod
    active: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/alura
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  config:
    prefix: "Bearer"
    key: "sYLzehcWaYf6JDWVM3UjlmgVsbeCxajA"
    expiration: 360000